# Generated by Django 3.2.6 on 2021-08-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
