# Generated by Django 3.2.6 on 2021-08-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_sku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
