# Generated by Django 3.2.6 on 2021-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210809_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
