# Generated by Django 3.2.6 on 2021-08-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
